backend = "glx";
vsync = true;

# Fade
corner-radius = 5;
shadow = true;
shadow-radius = 12;
shadow-opacity = 0.25;

#################################
#      Fading     #
#################################
fading = true;
fade-in-step = 0.044;
fade-out-step = 0.044;

#################################
#    ANIMATION     #
#################################
animations = true;
animation-stiffness = 100;     
animation-window-mass = 0.7;   
animation-dampening = 25;      
animation-clamping = false;    

# # #################################
# # #          Animations           #
# # #################################
# animations = ({
#    # triggers = ["open", "show"];
#    # preset = "appear";
#     duration = 0.5; # Faster for snappier feel on Ryzen 3
#     scale = 0.8;
# }, {
#    # triggers = ["close", "hide"];
#    # preset = "disappear";
#     duration = 0.5;
#     scale = 0.8;
# }, {
#     triggers = ["geometry"];
#     preset = "geometry-change";
#     duration = 0.7;
# })

#################################
#     Dual-Kawase Blur         #
#################################
blur: {
  method = "dual_kawase";
  strength = 4;
  background = true;
  background-frame = false;
  background-fixed = false;
}

blur-background-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS"
];